name: tests
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: intro message 
        run: echo "tests -- triggered by a ${{ github.event_name }} event to ${{ github.ref }} running on ${{ runner.os }} server"
      - name: set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # - name: install poetry
      #   run: |
      #     curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      #     source $HOME/.poetry/env
      - name: install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: latest
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: check out repository code
        uses: actions/checkout@v2
      - name: list files in the repository
        run: ls ${{ github.workspace }}
      - name: install repo
        run: poetry install
      - name: run tests
        run: poetry run python -m pytest --cov=umm tests/
      
